<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "works".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $user_id
 * @property integer $created_at
 * @property string $keywords
 * @property string $magazine_title
 * @property integer $deleted
 * @property string $hash
 */
class Articles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'articles';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'user_id', 'keywords', 'magazine_title'], 'required'],
            [['title', 'description', 'keywords', 'magazine_title', 'hash'], 'string'],
            [['user_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'description' => 'Описание',
            'keywords' => 'Ключевые слова',
            'magazine_title' => 'Название журнала',
            'created_at' => 'Дата добавления',
            'userCollaboration' => 'Соавтор'

        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getCollaboration()
    {
        return $this->hasMany(Collaboration::className(), ['article_id' => 'id']);
    }

    public function getUserCollaboration()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
            ->via('collaboration');
    }

    public function afterSave($insert)
    {
        $collaborations = $this->collaboration;

        if (Yii::$app->request->post('Articles')['userCollaboration']) {
            if (empty($collaborations)) {
                $collaboration = new Collaboration();
                $collaboration->article_id = $this->id;
            } else {
                $collaboration = $collaborations[0];
            }

            $collaboration->user_id = Yii::$app->request->post('Articles')['userCollaboration'];
            $collaboration->save(true);
        } elseif (isset(Yii::$app->request->post('Articles')['userCollaboration'])) {
            if (!empty($collaborations)) {
                foreach ($collaborations as $item) {
                    $item->delete();
                }
            }
        }

        return true;
    }

    public function afterDelete()
    {
        $this->collaboration;
        foreach ($this->collaboration as $item) {
            $item->delete();
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->hash = uniqid();
        }

        return true;
    }
}
